#cloud-config
package_update: true
packages:
  - openjdk-17-jdk

write_files:
  - path: /etc/systemd/system/digital-library.service
    content: |
      [Unit]
      Description=Digital Library Backend Service
      After=network.target
      StartLimitIntervalSec=500
      StartLimitBurst=5

      [Service]
      User=ubuntu
      WorkingDirectory=/home/ubuntu
      ExecStart=/usr/bin/java -jar /home/ubuntu/DigitalLibrary-0.0.1-SNAPSHOT.jar
      Environment="DB_URL=jdbc:postgresql://${db_host}:5432/webbooks"
      Environment="DB_USERNAME=${db_user}"
      Environment="DB_PASSWORD=${db_password}"
      Environment="SERVER_PORT=${app_port}"
      Restart=on-failure
      RestartSec=10s

      [Install]
      WantedBy=multi-user.target

runcmd:
  - echo 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' | tee -a /etc/environment
  - mkdir -p /home/ubuntu
  - chown -R ubuntu:ubuntu /home/ubuntu
  - systemctl daemon-reload
  - systemctl enable digital-library
