name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Позволяет запускать процесс вручную

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
          echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
          sudo apt-get install -y postgresql-12 postgresql-client-12
          sudo service postgresql start
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';"
          echo "listen_addresses = '*'" | sudo tee -a /etc/postgresql/12/main/postgresql.conf
          sudo systemctl restart postgresql.service
          sudo -u postgres psql -c "CREATE DATABASE webbooks;"
          sudo -u postgres psql webbooks < src/main/resources/data.sql

      - name: Build the application
        run: |
          cd webbooks
          ./mvnw package

      - name: Run the application
        run: |
          cd webbooks
          java -jar target/*.jar &
          sleep 10 # Даем приложению время на запуск

      - name: Check if application is running
        run: |
          curl -f http://localhost:8080 || exit 1
