name: Build and Upload to Yandex Cloud Storage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_ENDPOINT: 'storage.yandexcloud.net'
  S3_BUCKET: 'webbooks-artifacts'
  S3_FOLDER: 'artifacts'

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.6
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
      
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        
    - name: Configure S3 credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_KEY }}
      run: |
        mkdir -p ~/.aws
        cat > ~/.aws/config <<EOF
        [default]
        region = ru-central1
        s3 =
          endpoint_url = https://${{ env.S3_ENDPOINT }}
          signature_version = s3v4
        EOF
        
        cat > ~/.aws/credentials <<EOF
        [default]
        aws_access_key_id = $AWS_ACCESS_KEY_ID
        aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
        EOF
    
    - name: Upload to Yandex Cloud Storage
      run: |
        # Generate artifact name with timestamp and commit hash
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        COMMIT_HASH=$(git rev-parse --short HEAD)
        ARTIFACT_NAME="webbooks-${TIMESTAMP}-${COMMIT_HASH}.jar"
        
        # Rename and upload artifact
        mv target/*.jar ${ARTIFACT_NAME}
        aws --endpoint-url=https://${{ env.S3_ENDPOINT }} s3 cp \
          ${ARTIFACT_NAME} \
          s3://${{ env.S3_BUCKET }}/${{ env.S3_FOLDER }}/
        
        # Generate download URL
        echo "Download URL: https://${{ env.S3_ENDPOINT }}/${{ env.S3_BUCKET }}/${{ env.S3_FOLDER }}/${ARTIFACT_NAME}"
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
    
    - name: Output upload information
      run: |
        echo "Artifact successfully uploaded to Yandex Cloud Storage"
        echo "Artifact name: ${{ env.ARTIFACT_NAME }}"
        echo "Bucket: ${{ env.S3_BUCKET }}"
        echo "Full path: s3://${{ env.S3_BUCKET }}/${{ env.S3_FOLDER }}/${{ env.ARTIFACT_NAME }}"
